Gemfile
Gemfile.lock
app/api/schedule_exceptions_endpoints.rb
app/helpers/api_helper.rb
spec/helpers/api_helper_spec.rb

Add helper for pagination and make schedule_exceptions endpoint paginable

---

Gemfile
Gemfile.lock
app/api/events_endpoints.rb
app/interactors/api/compound_events.rb
app/interactors/api/paginate.rb
app/interactors/api/represent_events_json.rb
app/representers/events_representer.rb
spec/api/events_endpoints_spec.rb
spec/fabricators/event_fabricator.rb
spec/interactors/api/compound_events_spec.rb
spec/interactors/api/paginate_spec.rb
spec/interactors/api/represent_events_json_spec.rb
spec/spec_helper.rb
spec/support/have_only_keys_matcher.rb

Unlike the discussion in #96, I went with JSON-API recommendation and nested them under `"linked"` key.

Add compound resources

---

.env.sample
.env.test
.travis.yml
Gemfile
Gemfile.lock
README.md
Rakefile
app/api/base.rb
app/api/search_endpoints.rb
app/chewy/multi_search_index.rb
app/helpers/api_helper.rb
app/helpers/url_helper.rb
app/representers/search_results_representer.rb
app/roles/page_meta.rb
config/config.rb
config/initializers/chewy.rb
docs/Sirius.raml
lib/tasks/indexes.rake
lib/tasks/sirius.rake
script/setup
spec/api/search_endpoints_spec.rb
spec/api/semesters_endpoints_spec.rb
spec/helpers/url_helper_spec.rb
spec/integration/elasticsearch/multi_search_index_spec.rb
spec/integration/elasticsearch/spec_helper.rb
spec/interactors/import_updated_parallels_spec.rb
spec/roles/page_meta_spec.rb
spec/support/shared_examples_for_api.rb
spec/support/vcr.rb

Implement search resource using ElasticSearch

---

.travis.yml
Gemfile

So, you know, just so you notice.

Switch to Ruby 2.2.2

---

app/interactors/api/compound_events.rb
app/models/event.rb
app/models/parallel.rb
app/models/person.rb
config/initializers/database.rb

Use Sequel refinement for pg_array_op

---

app/api/events_endpoints.rb
app/interactors/api/compound_events.rb
app/interactors/api/represent_events_json.rb
app/representers/events_representer.rb
docs/Sirius.raml
spec/interactors/api/compound_events_spec.rb

What attributes of schedule exception should we include into compound document? @jnv @flexik

Add schedule_exceptions as compound documents into events

---

docs/schedule-exceptions.adoc

@flexik factual review plz
@jnv language review plz

Add documentation of schedule exceptions

---

config/config.rb
lib/sirius_api/strategies/remote_oauth_server.rb
spec/lib/sirius_api/strategies/remote_oauth_server_spec.rb

Use check_token instead of tokeninfo endpoint for validation of OAuth tokens

---

app/interactors/api/filter_events.rb
app/interactors/cleanup_removed_parallels.rb
app/interactors/convert_parallels.rb
app/interactors/convert_tts.rb
app/interactors/fetch_updated_parallels.rb
app/interactors/import_updated_parallels.rb
app/models/schedule_exception.rb
app/roles/planned_timetable_slot.rb
db/migrate/1443194817_add_deleted_at_to_parallels_and_timetable_slots.rb
db/schema.sql
lib/sirius/event_factory.rb
lib/sirius/schedule_manager.rb
lib/sirius/updated_parallels_finder.rb
spec/integration/schedule_manager_spec.rb
spec/interactors/api/filter_events_spec.rb
spec/interactors/cleanup_removed_parallels_spec.rb
spec/interactors/convert_parallels_spec.rb
spec/interactors/fetch_updated_parallels_spec.rb
spec/interactors/import_updated_parallels_spec.rb
spec/lib/sirius/updated_parallels_finder_spec.rb
spec/roles/planned_timetable_slot_spec.rb

This fixes #90 and should solve most of problems reported in #143.

Deleted parallels cleanup

---

app/interactors/cleanup_removed_parallels.rb
app/interactors/cleanup_removed_records.rb
app/interactors/cleanup_removed_timetable_slots.rb
app/interactors/convert_tts.rb
app/interactors/import_updated_parallels.rb
spec/fabricators/room_fabricator.rb
spec/interactors/cleanup_removed_timetable_slots_spec.rb
spec/interactors/convert_tts_spec.rb

This implements detection and marking of deleted timetable slots and should solve remaining data errors in #143.

Deleted timetableslots cleanup

---

app/models/person.rb
spec/models/person_spec.rb

Fix invalid input syntax for uuid error in Person.id_from_token()

---

.travis.yml
Gemfile
Gemfile.lock
README.md
config/config.rb
config/initializers/kosapi_client.rb
config/initializers/timeout.rb
lib/sirius_api/base_authorizer.rb
lib/sirius_api/events_authorizer.rb
lib/sirius_api/people_authorizer.rb
lib/sirius_api/scopes.rb
lib/sirius_api/strategies/local_token.rb
lib/sirius_api/strategies/remote_oauth_server.rb
lib/sirius_api/umapi_client.rb
lib/sirius_api/user.rb
spec/lib/sirius_api/events_authorizer_spec.rb
spec/lib/sirius_api/people_authorizer_spec.rb
spec/lib/sirius_api/strategies/remote_oauth_server_spec.rb
spec/lib/sirius_api/umapi_client_spec.rb
spec/lib/sirius_api/user_spec.rb
spec/support/kosapi_client_configurator.rb
spec/support/shared_context_for_api.rb

Refactor authorization, add some specs and fix #149

---

Gemfile
Gemfile.lock
config/config.rb
lib/sirius_api/umapi_client.rb
spec/lib/sirius_api/umapi_client_spec.rb
spec/support/shared_context_for_api.rb
spec/support/shared_examples_for_api.rb

This PR resolves #161 and #156.

Renew Umapi OAuth access token on 401 status

---

app/api/semesters_endpoints.rb
app/helpers/api_helper.rb
docs/Sirius.raml
lib/sirius_api/semester_filter.rb
spec/lib/sirius_api/semester_filter_spec.rb

I've implemented semester filtering by faculty id. This PR resolves #164.

Semester filtering

---

app/representers/semesters_representer.rb
db/migrate/1454511860_add_irregular_to_semester_periods.rb
db/schema.sql
db/seeds.rb
docs/Sirius.raml
spec/api/semesters_endpoints_spec.rb
spec/fabricators/semester_period_fabricator.rb

Add attribute irregular to SemesterPeriod (fixes #172)

---

app/api/events_endpoints.rb
app/interactors/api/represent_events_json.rb
app/models/event.rb
app/representers/events_representer.rb
docs/Sirius.raml
spec/api/events_endpoints_spec.rb
spec/interactors/api/represent_events_json_spec.rb
spec/models/event_spec.rb

This is needed to fix https://github.com/cvut/fittable/issues/236.

Add attribute “occupied” to Event and its JSON representation

---

app/api/faculties_endpoints.rb
app/api/semesters_endpoints.rb
docs/Sirius.raml
lib/sirius_api/semester_filter.rb
spec/api/faculties_endpoints_spec.rb
spec/api/semesters_endpoints_spec.rb
spec/api_spec_helper.rb
spec/lib/sirius_api/semester_filter_spec.rb
spec/support/shared_context_for_api.rb
spec/support/shared_examples_for_api.rb

Add resources /faculties/{code}/semesters and deprecate /semesters

---

docs/data-import-and-processing.adoc

This PR documents data import and processing in Sirius.
This is a first draft and definitely not a final version.

Document data import and processing

---

Gemfile
Gemfile.lock
app/interactors/convert_course_events.rb
app/interactors/convert_exams.rb
app/interactors/fetch_students.rb
app/interactors/import_course_events.rb
app/interactors/import_exams.rb
app/interactors/renumber_events.rb
app/interactors/sync.rb
app/models/schedule_exception.rb
app/roles/planned_timetable_slot.rb
config/initializers/database.rb
db/migrate/1465481874_create_audits_if_not_exists.rb
db/migrate/1465486180_split_source_in_events.rb
db/migrate/1467309659_import_event_functions.rb
db/migrate/1467309979_update_event_functions.rb
db/migrate/1467312179_remove_source_timetable_slot_id.rb
db/migrate/1467918523_add_absolute_sequence_numbers_to_course_events_exams.rb
db/schema.sql
lib/actors/event_destination.rb
lib/actors/teacher_timetable_slot_transformer.rb
lib/sirius/event_factory.rb
lib/sirius/event_planner.rb
spec/interactors/convert_exams_spec.rb
spec/interactors/fetch_students_spec.rb
spec/interactors/sync_spec.rb
spec/lib/sirius/event_planner_spec.rb
spec/models/schedule_exception_spec.rb
spec/roles/planned_timetable_slot_spec.rb

Upsert updates (rebased)

---

app/api/events_endpoints.rb
app/interactors/api/filter_events.rb
spec/api/events_endpoints_spec.rb
spec/fabricators/event_fabricator.rb
spec/interactors/api/filter_events_spec.rb

Hack URI parameter "deleted" to accept "all" for keeping all events

---

app/representers/semesters_representer.rb
db/migrate/1499120813_add_name_to_semester_periods.rb
db/schema.sql
docs/Sirius.raml
spec/api/faculties_endpoints_spec.rb
spec/api/semesters_endpoints_spec.rb
spec/fabricators/semester_period_fabricator.rb

⚠️ Includes commits from #222, this PR starts by commit 27f676b.

Add "name" to semester_periods table and representer

---

Gemfile
Gemfile.lock

Use role_playing from RubyGems
